outpath: output

ref_sample_rates:
    - "0.01"
    - "0.25"
    - "0.50"
    - "0.75"
    - "1.00"

freddie:
    exec: extern/freddie/freddie.py
    rname_to_celltypes: py/rname_to_celltypes.py

FLAMES:
    src: extern/FLAMES/src
    exec: extern/FLAMES/python/sc_long_pipeline.py

scNanoGPS:
    profile: "extern/scNanoGPS/other_utils/read_length_profiler.py"
    read_qc: "extern/scNanoGPS/other_utils/prepare_read_qc.py"
    scan: "extern/scNanoGPS/scanner.py"
    assign: "extern/scNanoGPS/assigner.py"
    curate: "extern/scNanoGPS/curator.py"
    expression: "extern/scNanoGPS/reporter_expression.py"
    isoforms: "extern/scNanoGPS/reporter_isoform.py"

TKSM:
    exec: tksm
    outpath: output/simulate
    enable_piping: false
    experiments:
        Expr1:
            pipeline:
                - Mrg:
                      sources: ["A500", "B500", "C500", "D500", "E500"]
                - plA:
                      params: "--normal=15,7.5"
                - Tag:
                      params: "--format3 10"
                - SCB:
                      params: ""
                - Tag:
                      params: "--format5 AAGCAGTGGTATCAACGCAGAGTACATGGG --format3 AGATCGGAAGAGCGTCGTGTAG"
                - PCR:
                      params: "--cycles 5 --molecule-count 5000000 -x Taq-setting1"
                - Flp:
                      params: "-p 0.5"
                - Tag:
                      params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
                - Trc:
                      params: ""
                      model: MCF7
                - Shf:
                      params: ""
                - Seq:
                      params: "--skip-qual-compute"
        Expr2:
            pipeline:
                - Mrg:
                      sources: ["A1000", "B250", "C250", "D250", "E250"]
                - plA:
                      params: "--normal=15,7.5"
                - Tag:
                      params: "--format3 10"
                - SCB:
                      params: ""
                - Tag:
                      params: "--format5 AAGCAGTGGTATCAACGCAGAGTACATGGG --format3 AGATCGGAAGAGCGTCGTGTAG"
                - PCR:
                      params: "--cycles 5 --molecule-count 5000000 -x Taq-setting1"
                - Flp:
                      params: "-p 0.5"
                - Tag:
                      params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
                - Trc:
                      params: ""
                      model: MCF7
                - Shf:
                      params: ""
                - Seq:
                      params: "--skip-qual-compute"
        Expr3:
            pipeline:
                - Mrg:
                      sources: ["A1000", "B1000", "C1000"]
                - plA:
                      params: "--normal=15,7.5"
                - Tag:
                      params: "--format3 10"
                - SCB:
                      params: ""
                - Tag:
                      params: "--format5 AAGCAGTGGTATCAACGCAGAGTACATGGG --format3 AGATCGGAAGAGCGTCGTGTAG"
                - PCR:
                      params: "--cycles 5 --molecule-count 5000000 -x Taq-setting1"
                - Flp:
                      params: "-p 0.5"
                - Tag:
                      params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
                - Trc:
                      params: ""
                      model: MCF7
                - Shf:
                      params: ""
                - Seq:
                      params: "--skip-qual-compute"
        Expr4:
            pipeline:
                - Mrg:
                      sources: ["A1000", "B1000", "C1000", "D1000", "E1000"]
                - plA:
                      params: "--normal=15,7.5"
                - Tag:
                      params: "--format3 10"
                - SCB:
                      params: ""
                - Tag:
                      params: "--format5 AAGCAGTGGTATCAACGCAGAGTACATGGG --format3 AGATCGGAAGAGCGTCGTGTAG"
                - PCR:
                      params: "--cycles 5 --molecule-count 5000000 -x Taq-setting1"
                - Flp:
                      params: "-p 0.5"
                - Tag:
                      params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
                - Trc:
                      params: ""
                      model: MCF7
                - Shf:
                      params: ""
                - Seq:
                      params: "--skip-qual-compute"
        Expr5:
            pipeline:
                - Mrg:
                      sources: ["A250", "B250", "C250", "D250", "E250"]
                - plA:
                      params: "--normal=15,7.5"
                - Tag:
                      params: "--format3 10"
                - SCB:
                      params: ""
                - Tag:
                      params: "--format5 AAGCAGTGGTATCAACGCAGAGTACATGGG --format3 AGATCGGAAGAGCGTCGTGTAG"
                - PCR:
                      params: "--cycles 5 --molecule-count 5000000 -x Taq-setting1"
                - Flp:
                      params: "-p 0.5"
                - Tag:
                      params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
                - Trc:
                      params: ""
                      model: MCF7
                - Shf:
                      params: ""
                - Seq:
                      params: "--skip-qual-compute"
        A250:
            pipeline:
                - Tsb:
                      params: "--molecule-count 250000 --molecule-prefix A250: -s 251"
                      model: A250
        B250:
            pipeline:
                - Tsb:
                      params: "--molecule-count 250000 --molecule-prefix B250: -s 252"
                      model: B250
        C250:
            pipeline:
                - Tsb:
                      params: "--molecule-count 250000 --molecule-prefix C250: -s 253"
                      model: C250
        D250:
            pipeline:
                - Tsb:
                      params: "--molecule-count 250000 --molecule-prefix D250: -s 254"
                      model: D250
        E250:
            pipeline:
                - Tsb:
                      params: "--molecule-count 250000 --molecule-prefix E250: -s 255"
                      model: E250
        A500:
            pipeline:
                - Tsb:
                      params: "--molecule-count 500000 --molecule-prefix A500: -s 251"
                      model: A500
        B500:
            pipeline:
                - Tsb:
                      params: "--molecule-count 500000 --molecule-prefix B500: -s 252"
                      model: B500
        C500:
            pipeline:
                - Tsb:
                      params: "--molecule-count 500000 --molecule-prefix C500: -s 253"
                      model: C500
        D500:
            pipeline:
                - Tsb:
                      params: "--molecule-count 500000 --molecule-prefix D500: -s 254"
                      model: D500
        E500:
            pipeline:
                - Tsb:
                      params: "--molecule-count 500000 --molecule-prefix E500: -s 255"
                      model: E500
        A1000:
            pipeline:
                - Tsb:
                      params: "--molecule-count 1000000 --molecule-prefix A1000: -s 251"
                      model: A1000
        B1000:
            pipeline:
                - Tsb:
                      params: "--molecule-count 1000000 --molecule-prefix B1000: -s 252"
                      model: B1000
        C1000:
            pipeline:
                - Tsb:
                      params: "--molecule-count 1000000 --molecule-prefix C1000: -s 253"
                      model: C1000
        D1000:
            pipeline:
                - Tsb:
                      params: "--molecule-count 1000000 --molecule-prefix D1000: -s 254"
                      model: D1000
        E1000:
            pipeline:
                - Tsb:
                      params: "--molecule-count 1000000 --molecule-prefix E1000: -s 255"
                      model: E1000
    refs:
        Homo_sapiens:
            GTF: data/refs/homo_sapiens.annot.gtf
            DNA: data/refs/homo_sapiens.dna.fa
            cDNA: data/refs/homo_sapiens.cdna.fa
        barcodes:
            10x: data/refs/3M-february-2018.txt.gz
    samples:
        A549:
            fastq:
                - data/samples/SGNex_A549_directcDNA_replicate1_run3.fastq.gz
            ref: Homo_sapiens
        Hct116:
            fastq:
                - data/samples/SGNex_Hct116_directcDNA_replicate4_run1.fastq.gz
            ref: Homo_sapiens
        HepG2:
            fastq:
                - data/samples/SGNex_HepG2_directcDNA_replicate5_run3.fastq.gz
            ref: Homo_sapiens
        K562:
            fastq:
                - data/samples/SGNex_K562_directcDNA_replicate1_run2.fastq.gz
            ref: Homo_sapiens
        MCF7:
            fastq:
                - data/samples/SGNex_MCF7_cDNA_replicate1_run3.fastq.gz
            ref: Homo_sapiens
    models:
        Tsb:
            A250:
                sample: A549
                cb-txt: 10x
                params: "--cb-count 250  --cb-dropout 0.0 --random-seed 251"
            A500:
                sample: A549
                cb-txt: 10x
                params: "--cb-count 500  --cb-dropout 0.0 --random-seed 501"
            A1000:
                sample: A549
                cb-txt: 10x
                params: "--cb-count 1000  --cb-dropout 0.0 --random-seed 1001"
            B250:
                sample: Hct116
                cb-txt: 10x
                params: "--cb-count 250  --cb-dropout 0.0 --random-seed 252"
            B500:
                sample: Hct116
                cb-txt: 10x
                params: "--cb-count 500  --cb-dropout 0.0 --random-seed 502"
            B1000:
                sample: Hct116
                cb-txt: 10x
                params: "--cb-count 1000  --cb-dropout 0.0 --random-seed 1002"
            C250:
                sample: HepG2
                cb-txt: 10x
                params: "--cb-count 250  --cb-dropout 0.0 --random-seed 253"
            C500:
                sample: HepG2
                cb-txt: 10x
                params: "--cb-count 500  --cb-dropout 0.0 --random-seed 503"
            C1000:
                sample: HepG2
                cb-txt: 10x
                params: "--cb-count 1000  --cb-dropout 0.0 --random-seed 1003"
            D250:
                sample: K562
                cb-txt: 10x
                params: "--cb-count 250  --cb-dropout 0.0 --random-seed 254"
            D500:
                sample: K562
                cb-txt: 10x
                params: "--cb-count 500  --cb-dropout 0.0 --random-seed 504"
            D1000:
                sample: K562
                cb-txt: 10x
                params: "--cb-count 1000  --cb-dropout 0.0 --random-seed 1004"
            E250:
                sample: MCF7
                cb-txt: 10x
                params: "--cb-count 250  --cb-dropout 0.0 --random-seed 255"
            E500:
                sample: MCF7
                cb-txt: 10x
                params: "--cb-count 500  --cb-dropout 0.0 --random-seed 505"
            E1000:
                sample: MCF7
                cb-txt: 10x
                params: "--cb-count 1000  --cb-dropout 0.0 --random-seed 1005"
