outpath: output/real

ref_sample_rates:
    - "1.00"
    - "0.75"
    - "0.50"
    - "0.25"
    - "0.01"

freddie:
    exec: extern/freddie/freddie.py
    rname_to_celltypes: py/rname_to_celltypes.py

FLAMES:
    src: extern/FLAMES/src
    exec: extern/FLAMES/python/sc_long_pipeline.py

scNanoGPS:
    profile: "extern/scNanoGPS/other_utils/read_length_profiler.py"
    read_qc: "extern/scNanoGPS/other_utils/prepare_read_qc.py"
    scan: "extern/scNanoGPS/scanner.py"
    assign: "extern/scNanoGPS/assigner.py"
    curate: "extern/scNanoGPS/curator.py"
    expression: "extern/scNanoGPS/reporter_expression.py"
    isoforms: "extern/scNanoGPS/reporter_isoform.py"

samples:
    scmixology2:
        cb_to_celltype: "data/samples/scmixology2_cell-line_to_barcode.tsv"
        DNA: "data/refs/homo_sapiens.dna.fa"
        GTF: "data/refs/homo_sapiens.annot.gtf"
        CB: "data/refs/scmixology2.txt.gz"
        FASTQ: "data/samples/ERR9958136_first_1M_reads.fastq"
        rna_srs:
            H838_1: "data/samples/SRR4113668.fastq.gz"
            H838_2: "data/samples/SRR4113669.fastq.gz"
            H2228_1: "data/samples/SRR4113666.fastq.gz"
            H2228_2: "data/samples/SRR4113667.fastq.gz"
            HCC82_1: "data/samples/SRR4113664.fastq.gz"
            HCC82_2: "data/samples/SRR4113665.fastq.gz"
            H1975_1: "data/samples/SRR4113662.fastq.gz"
            H1975_2: "data/samples/SRR4113663.fastq.gz"
            A549_1: "data/samples/SRR4113660.fastq.gz"
            A549_2: "data/samples/SRR4113661.fastq.gz"
